[package]
name = "stars"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stars"
test = false
bench = false

[profile.release]
panic = "abort"

[dependencies.app-lib]
path = "../app-lib/app-lib"

[dependencies]
rand = { version = "0.8", default_features = false, features = ["small_rng"] }
