[build]
target = "x86_64-unknown-none"

rustflags = [
	"-C",
	"code-model=large",
	"-C",
	"relocation-model=static",
	"-C",
	"link-arg=--entry=_start",
	"-C",
	"link-arg=-z norelro",
	"-C",
	"link-arg=--image-base=0xffff800000000000",
	"-C",
	"link-arg=--static",
]
